version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  producer:
    build:
      context: .
      dockerfile: docker/producer.Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: events
    depends_on:
      - kafka

  spark-stream:
    build:
      context: .
      dockerfile: docker/spark-stream.Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: events
    depends_on:
      - kafka

