apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-stream
  template:
    metadata:
      labels:
        app: spark-stream
    spec:
      containers:
        - name: spark-stream
          image: spark-stream:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: events

