apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-producer
  template:
    metadata:
      labels:
        app: data-producer
    spec:
      containers:
        - name: producer
          image: data-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: events

